name = "catppuccin"
display-name = "Catppuccin"
description = "üê≠ Soothing pastel theme for Lapce"
version = "0.1.11"
author = "catppuccin"
repository = "catppuccin/lapce"
icon = "assets/logo.webp"
color-themes = ["catppuccin-latte.toml", "catppuccin-frappe.toml", "catppuccin-macchiato.toml", "catppuccin-mocha.toml"]
